"""Measure detector false-positive / false-negative rates on a labelled synthetic set.

Positives: the canonical 'valid' formation for each pattern, re-generated with many
noise seeds and two noise levels. Negatives: flat noise, steady trends and random
walks (labelled negative for *confirmed* formations of that pattern; note random
walks can legitimately contain real patterns, so their FP rate is an upper bound).

    python scripts/evaluate_detectors.py  [--out ../docs/DETECTOR_EVALUATION.md]

This is a synthetic benchmark, not a validation on real PSX data. A labelled set of
real charts (user-supplied, licensed) should be evaluated the same way.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.chart_patterns.registry import detect_patterns  # noqa: E402
from app.data_providers.synthetic import make_ohlcv, random_walk  # noqa: E402
from app.schemas.patterns import PatternStage  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "tests"))
from pattern_fixtures import ASC_TRIANGLE, BULL_FLAG, DOUBLE_TOP, HEAD_SHOULDERS, SYM_TRIANGLE, mirror  # noqa: E402
from test_phase2_patterns import VALID as PHASE2  # noqa: E402

CONF = (PatternStage.CONFIRMED, PatternStage.RETESTING)
CASES = [
    ("double_top", DOUBLE_TOP["valid"]), ("double_bottom", mirror(DOUBLE_TOP["valid"])),
    ("head_and_shoulders", HEAD_SHOULDERS["valid"]), ("inverse_head_and_shoulders", mirror(HEAD_SHOULDERS["valid"])),
    ("ascending_triangle", ASC_TRIANGLE["valid"]), ("descending_triangle", mirror(ASC_TRIANGLE["valid"])),
    ("symmetrical_triangle", SYM_TRIANGLE["valid_up"]), ("bull_flag", BULL_FLAG["valid"]), ("bear_flag", mirror(BULL_FLAG["valid"])),
] + [(pid, wp) for pid, wp, _ in PHASE2]


def confirmed(df, pid):
    return any(r.pattern_id == pid and r.stage in CONF for r in detect_patterns(df))


def main(out: Path | None, seeds: int) -> None:
    negs = []
    for s in range(seeds):
        negs.append(make_ohlcv([(0, 100), (160, 100)], seed=100 + s, noise=0.3))
        negs.append(make_ohlcv([(0, 100), (160, 150)], seed=200 + s, noise=0.3))
        negs.append(make_ohlcv([(0, 150), (160, 100)], seed=300 + s, noise=0.3))
    walks = [random_walk(300, seed=400 + s) for s in range(seeds)]
    neg_res = [{r.pattern_id for r in detect_patterns(d) if r.stage in CONF} for d in negs]
    walk_res = [{r.pattern_id for r in detect_patterns(d) if r.stage in CONF} for d in walks]
    lines = ["| Pattern | Recall (noise 0.25) | Recall (noise 0.5) | FP rate: flat/trend | Confirmations in random walks |",
             "|---|---:|---:|---:|---:|"]
    for pid, wp in CASES:
        r1 = sum(confirmed(make_ohlcv(wp, seed=s), pid) for s in range(seeds)) / seeds
        r2 = sum(confirmed(make_ohlcv(wp, seed=s, noise=0.5, wick=0.6), pid) for s in range(seeds)) / seeds
        fp = sum(pid in x for x in neg_res) / len(neg_res)
        rw = sum(pid in x for x in walk_res) / len(walk_res)
        lines.append(f"| {pid} | {r1:.0%} | {r2:.0%} | {fp:.0%} | {rw:.0%} |")
        print(lines[-1])
    if out:
        out.write_text("# Detector evaluation (synthetic benchmark)\n\n"
                       f"Generated by `backend/scripts/evaluate_detectors.py` with {seeds} seeds per cell.\n\n"
                       "* **Recall**: share of noisy re-generations of the canonical formation detected as CONFIRMED.\n"
                       "* **FP rate**: share of flat-noise / steady-trend series (no formation) with a CONFIRMED detection.\n"
                       "* **Random walks** can contain genuine formations by chance, so that column is an upper bound "
                       "on false positives, not a pure FP rate.\n\n"
                       "Limitations: synthetic formations are idealised; real-market performance must be measured on a "
                       "separately labelled set of real PSX charts. Noise 0.5 roughly doubles bar-to-bar noise relative "
                       "to the formation amplitude and shows degradation.\n\n" + "\n".join(lines) + "\n")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=Path(__file__).resolve().parents[2] / "docs" / "DETECTOR_EVALUATION.md")
    ap.add_argument("--seeds", type=int, default=20)
    a = ap.parse_args()
    main(a.out, a.seeds)
