"""Generate the offline demo datasets in fixtures/sample_data/.

All files are SYNTHETIC (symbol prefix ``SYN-``) and labelled as such through a
``.meta.json`` sidecar. They exist so the platform runs end-to-end without a
licensed data feed. They are NOT PSX prices.

    python scripts/generate_sample_data.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.data_providers.synthetic import make_ohlcv  # noqa: E402
from app.data_validation.calendar import PKT, load_holidays  # noqa: E402

OUT = Path(__file__).resolve().parents[1] / "fixtures" / "sample_data"
END = "2026-10-07"


def index_ending(n: int, end: str = END) -> pd.DatetimeIndex:
    hol = load_holidays()
    days = [d for d in pd.bdate_range(end=end, periods=int(n * 1.1) + 20) if d.date() not in hol][-n:]
    return pd.DatetimeIndex(days, name="timestamp").tz_localize(PKT)


def wander(seed: int, start: float, legs: int, leg_len=(12, 30), amp=0.12, drift=0.0) -> list[tuple[int, float]]:
    rng = np.random.default_rng(seed)
    wp, i, p = [(0, start)], 0, start
    for _ in range(legs):
        i += int(rng.integers(*leg_len))
        p = max(5.0, p * (1 + rng.normal(drift, amp)))
        wp.append((i, p))
    return wp


SCENARIOS = {
    "SYN-DBOT": dict(desc="Downtrend into a confirmed double bottom", seed=11, start=160, legs=14, drift=-0.03,
                     pattern=[(0, 1.0), (25, 0.80), (40, 0.90), (55, 0.80), (75, 0.97)], spikes={68: 2.4}),
    "SYN-HS": dict(desc="Advance into a head & shoulders approaching its neckline", seed=21, start=60, legs=14,
                   drift=0.03, pattern=[(0, 1.0), (30, 1.20), (40, 1.10), (55, 1.32), (70, 1.10), (85, 1.20), (95, 1.12)]),
    "SYN-ASCT": dict(desc="Ascending triangle pressing on resistance", seed=31, start=95, legs=14, drift=0.01,
                     pattern=[(0, 1.0), (25, 1.18), (40, 1.28), (50, 1.18), (60, 1.28), (68, 1.22), (76, 1.28),
                              (82, 1.25), (88, 1.275)]),
    "SYN-FLAG": dict(desc="Strong rally followed by a bull flag breakout", seed=41, start=40, legs=14, drift=0.02,
                     pattern=[(0, 1.0), (12, 1.25), (15, 1.21), (18, 1.235), (21, 1.20), (24, 1.22), (27, 1.19),
                              (30, 1.205), (35, 1.31)], spikes={33: 2.2}),
    "SYN-RANGE": dict(desc="Sideways range, no dominant pattern", seed=51, start=250, legs=18, drift=0.0, pattern=[(0, 1.0), (20, 1.02)]),
}


def build(name: str, sc: dict) -> pd.DataFrame:
    prefix = wander(sc["seed"], sc["start"], sc["legs"], drift=sc["drift"])
    i0, p0 = prefix[-1]
    wp = prefix + [(i0 + i, p0 * r) for i, r in sc["pattern"][1:]]
    n = int(wp[-1][0]) + 1
    noise = 0.004 * np.mean([p for _, p in wp])
    spikes = {i0 + k: v for k, v in sc.get("spikes", {}).items()}
    return make_ohlcv(wp, noise=noise, wick=noise * 1.6, seed=sc["seed"], volume=800_000, volume_spikes=spikes,
                      index=index_ending(n))


def build_intraday(daily: pd.DataFrame, days: int = 30, seed: int = 99) -> pd.DataFrame:
    """15-minute synthetic bars (09:30-15:30 PKT) consistent in scale with the daily series."""
    rng = np.random.default_rng(seed)
    rows = []
    for ts, d in daily.tail(days).iterrows():
        slots = pd.date_range(ts + pd.Timedelta(hours=9, minutes=30), ts + pd.Timedelta(hours=15, minutes=15), freq="15min")
        path = np.linspace(d["open"], d["close"], len(slots) + 1)
        path[1:-1] += rng.normal(0, (d["high"] - d["low"]) * 0.15, len(slots) - 1)
        for k, s in enumerate(slots):
            o, c = path[k], path[k + 1]
            hi = min(d["high"], max(o, c) + abs(rng.normal(0, (d["high"] - d["low"]) * 0.05)))
            lo = max(d["low"], min(o, c) - abs(rng.normal(0, (d["high"] - d["low"]) * 0.05)))
            rows.append((s, o, max(hi, o, c), min(lo, o, c), c, round(d["volume"] / len(slots) * rng.uniform(0.5, 1.5))))
    return pd.DataFrame(rows, columns=["timestamp", "open", "high", "low", "close", "volume"]).set_index("timestamp")


def write(df: pd.DataFrame, sym: str, tf: str, desc: str) -> None:
    path = OUT / f"{sym}_{tf}.csv"
    out = df.reset_index()
    out["timestamp"] = out["timestamp"].astype(str)
    with path.open("w") as fh:
        fh.write("# SYNTHETIC DEMO DATA - NOT REAL PSX PRICES\n")
        out.round(4).to_csv(fh, index=False)
    path.with_suffix(".meta.json").write_text(json.dumps({
        "attribution": "SYNTHETIC DEMO DATA generated by scripts/generate_sample_data.py - NOT real PSX prices.",
        "synthetic": True, "adjusted": True, "notes": [desc]}, indent=2))


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for sym, sc in SCENARIOS.items():
        daily = build(sym, sc)
        write(daily, sym, "1d", sc["desc"])
        if sym == "SYN-FLAG":
            write(build_intraday(daily), sym, "15m", "Synthetic 15-minute bars for intraday demo")
        print(f"{sym}: {len(daily)} daily bars, last close {daily['close'].iloc[-1]:.2f}")


if __name__ == "__main__":
    main()
